language: go

go:
  - 1.0
  - 1.1
  - 1.2 
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - go get -u github.com/axw/gocov/gocov
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/golang/lint

script:
  - diff -u <(echo -n) <(gofmt -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - diff -u <(echo -n) <(golint ./...)
  - go test -v -race -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
